Search.appendIndex(
    [
                {
            "fqsen": "\\BizCuit\\BexioCTX",
            "name": "BexioCTX",
            "summary": "Base\u0020class\u0020containing\u0020cURL\u0020operations.",
            "url": "classes/BizCuit-BexioCTX.html"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020the\u0020context\u0020with\u0020API\u0020token\u0020needed\u0020to\u0020access\u0020endpoints",
            "url": "classes/BizCuit-BexioCTX.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003Aset_url\u0028\u0029",
            "name": "set_url",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#method_set_url"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003Aset_method\u0028\u0029",
            "name": "set_method",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#method_set_method"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003Aset_body\u0028\u0029",
            "name": "set_body",
            "summary": "Set\u0020the\u0020request\u0020body\u0020if\u0020any.",
            "url": "classes/BizCuit-BexioCTX.html#method_set_body"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#method_reset"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#method___set"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#method___get"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003A__isset\u0028\u0029",
            "name": "__isset",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#method___isset"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003A__unset\u0028\u0029",
            "name": "__unset",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#method___unset"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003Afetch\u0028\u0029",
            "name": "fetch",
            "summary": "Execute\u0020the\u0020request.",
            "url": "classes/BizCuit-BexioCTX.html#method_fetch"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003Aendpoint",
            "name": "endpoint",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#constant_endpoint"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003A\u0024c",
            "name": "c",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#property_c"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#property_headers"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003A\u0024values",
            "name": "values",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#property_values"
        },                {
            "fqsen": "\\BizCuit\\BexioCTX\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/BizCuit-BexioCTX.html#property_token"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI",
            "name": "BexioAPI",
            "summary": "Base\u0020class\u0020for\u0020enpdoints.",
            "url": "classes/BizCuit-BexioAPI.html"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020withing\u0020the\u0020given\u0020context.",
            "url": "classes/BizCuit-BexioAPI.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003AsetCurrentUser\u0028\u0029",
            "name": "setCurrentUser",
            "summary": "Set\u0020current\u0020user\u0020id.",
            "url": "classes/BizCuit-BexioAPI.html#method_setCurrentUser"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003AsetCurrentOwner\u0028\u0029",
            "name": "setCurrentOwner",
            "summary": "Set\u0020current\u0020owner\u0020id.",
            "url": "classes/BizCuit-BexioAPI.html#method_setCurrentOwner"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Get\u0020the\u0020current\u0020type.",
            "url": "classes/BizCuit-BexioAPI.html#method_getType"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003A\u0024endpoint",
            "name": "endpoint",
            "summary": "",
            "url": "classes/BizCuit-BexioAPI.html#property_endpoint"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003A\u0024c",
            "name": "c",
            "summary": "",
            "url": "classes/BizCuit-BexioAPI.html#property_c"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003A\u0024userid",
            "name": "userid",
            "summary": "",
            "url": "classes/BizCuit-BexioAPI.html#property_userid"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003A\u0024ownerid",
            "name": "ownerid",
            "summary": "",
            "url": "classes/BizCuit-BexioAPI.html#property_ownerid"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/BizCuit-BexioAPI.html#property_headers"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioAPI.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003A\u0024ctx",
            "name": "ctx",
            "summary": "",
            "url": "classes/BizCuit-BexioAPI.html#property_ctx"
        },                {
            "fqsen": "\\BizCuit\\BexioAPI\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioAPI.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioCountry",
            "name": "BexioCountry",
            "summary": "Represent\u0020the\u0020enpoint\u0020Countries",
            "url": "classes/BizCuit-BexioCountry.html"
        },                {
            "fqsen": "\\BizCuit\\BexioCountry\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioCountry.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioCountry\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioCountry.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioCountry\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioCountry.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioQuote",
            "name": "BexioQuote",
            "summary": "Represent\u0020the\u0020enpoint\u0020Quotes",
            "url": "classes/BizCuit-BexioQuote.html"
        },                {
            "fqsen": "\\BizCuit\\BexioQuote\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioQuote.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioQuote\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioQuote.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioQuote\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioQuote.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioInvoice",
            "name": "BexioInvoice",
            "summary": "Represent\u0020the\u0020enpoint\u0020Invoices",
            "url": "classes/BizCuit-BexioInvoice.html"
        },                {
            "fqsen": "\\BizCuit\\BexioInvoice\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioInvoice.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioInvoice\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioInvoice.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioInvoice\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioInvoice.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioOrder",
            "name": "BexioOrder",
            "summary": "Represent\u0020the\u0020enpoint\u0020Orders",
            "url": "classes/BizCuit-BexioOrder.html"
        },                {
            "fqsen": "\\BizCuit\\BexioOrder\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioOrder.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioOrder\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioOrder.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioOrder\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioOrder.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioContact",
            "name": "BexioContact",
            "summary": "Represent\u0020the\u0020enpoint\u0020Contacts",
            "url": "classes/BizCuit-BexioContact.html"
        },                {
            "fqsen": "\\BizCuit\\BexioContact\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioContact.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioContact\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioContact.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioContact\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioContact.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioProject",
            "name": "BexioProject",
            "summary": "Represent\u0020the\u0020enpoint\u0020Projects",
            "url": "classes/BizCuit-BexioProject.html"
        },                {
            "fqsen": "\\BizCuit\\BexioProject\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioProject.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioProject\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioProject.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioProject\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioProject.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioContactRelation",
            "name": "BexioContactRelation",
            "summary": "Represent\u0020the\u0020enpoint\u0020Contact\u0020Relations",
            "url": "classes/BizCuit-BexioContactRelation.html"
        },                {
            "fqsen": "\\BizCuit\\BexioContactRelation\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioContactRelation.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioContactRelation\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioContactRelation.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioContactRelation\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioContactRelation.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioAdditionalAddress",
            "name": "BexioAdditionalAddress",
            "summary": "Represent\u0020the\u0020enpoint\u0020Additional\u0020Addresses",
            "url": "classes/BizCuit-BexioAdditionalAddress.html"
        },                {
            "fqsen": "\\BizCuit\\BexioAdditionalAddress\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioAdditionalAddress.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioAdditionalAddress\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioAdditionalAddress.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioAdditionalAddress\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioAdditionalAddress.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioNote",
            "name": "BexioNote",
            "summary": "Represent\u0020the\u0020enpoint\u0020Notes",
            "url": "classes/BizCuit-BexioNote.html"
        },                {
            "fqsen": "\\BizCuit\\BexioNote\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioNote.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioNote\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioNote.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioNote\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioNote.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioUser",
            "name": "BexioUser",
            "summary": "Represent\u0020the\u0020enpoint\u0020User\u0020Management",
            "url": "classes/BizCuit-BexioUser.html"
        },                {
            "fqsen": "\\BizCuit\\BexioUser\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioUser.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioUser\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioUser.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioUser\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioUser.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioBusinessActivity",
            "name": "BexioBusinessActivity",
            "summary": "Represent\u0020the\u0020enpoint\u0020Business\u0020Activities",
            "url": "classes/BizCuit-BexioBusinessActivity.html"
        },                {
            "fqsen": "\\BizCuit\\BexioBusinessActivity\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioBusinessActivity.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioBusinessActivity\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioBusinessActivity.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioBusinessActivity\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioBusinessActivity.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioSalutation",
            "name": "BexioSalutation",
            "summary": "Represent\u0020the\u0020enpoint\u0020Salutations",
            "url": "classes/BizCuit-BexioSalutation.html"
        },                {
            "fqsen": "\\BizCuit\\BexioSalutation\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioSalutation.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioSalutation\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioSalutation.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioSalutation\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioSalutation.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioTitle",
            "name": "BexioTitle",
            "summary": "Represent\u0020the\u0020enpoint\u0020Titles",
            "url": "classes/BizCuit-BexioTitle.html"
        },                {
            "fqsen": "\\BizCuit\\BexioTitle\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioTitle.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioTitle\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioTitle.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioTitle\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioTitle.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioProjectType",
            "name": "BexioProjectType",
            "summary": "Represent\u0020the\u0020enpoint\u0020Project\u0020Types",
            "url": "classes/BizCuit-BexioProjectType.html"
        },                {
            "fqsen": "\\BizCuit\\BexioProjectType\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioProjectType.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioProjectType\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioProjectType.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioProjectType\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioProjectType.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioProjectStatus",
            "name": "BexioProjectStatus",
            "summary": "Represent\u0020the\u0020enpoint\u0020Project\u0020Status",
            "url": "classes/BizCuit-BexioProjectStatus.html"
        },                {
            "fqsen": "\\BizCuit\\BexioProjectStatus\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioProjectStatus.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioProjectStatus\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioProjectStatus.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioProjectStatus\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioProjectStatus.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioBills",
            "name": "BexioBills",
            "summary": "Represent\u0020the\u0020enpoint\u0020Bills",
            "url": "classes/BizCuit-BexioBills.html"
        },                {
            "fqsen": "\\BizCuit\\BexioBills\u003A\u003AsetStatus\u0028\u0029",
            "name": "setStatus",
            "summary": "",
            "url": "classes/BizCuit-BexioBills.html#method_setStatus"
        },                {
            "fqsen": "\\BizCuit\\BexioBills\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioBills.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioBills\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioBills.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioBills\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioBills.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioBills\u003A\u003A\u0024search_fields",
            "name": "search_fields",
            "summary": "",
            "url": "classes/BizCuit-BexioBills.html#property_search_fields"
        },                {
            "fqsen": "\\BizCuit\\BexioFile",
            "name": "BexioFile",
            "summary": "Represent\u0020the\u0020enpoint\u0020Files",
            "url": "classes/BizCuit-BexioFile.html"
        },                {
            "fqsen": "\\BizCuit\\BexioFile\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/BizCuit-BexioFile.html#method_getId"
        },                {
            "fqsen": "\\BizCuit\\BexioFile\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020a\u0020file\u0020from\u0020file\u0020endpoint.",
            "url": "classes/BizCuit-BexioFile.html#method_get"
        },                {
            "fqsen": "\\BizCuit\\BexioFile\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/BizCuit-BexioFile.html#property_type"
        },                {
            "fqsen": "\\BizCuit\\BexioFile\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/BizCuit-BexioFile.html#property_class"
        },                {
            "fqsen": "\\BizCuit\\BexioFile\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BexioFile.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BexioFile\u003A\u003A\u0024uuid",
            "name": "uuid",
            "summary": "",
            "url": "classes/BizCuit-BexioFile.html#property_uuid"
        },                {
            "fqsen": "\\BizCuit\\tBexioV2Api",
            "name": "tBexioV2Api",
            "summary": "",
            "url": "classes/BizCuit-tBexioV2Api.html"
        },                {
            "fqsen": "\\BizCuit\\tBexioV2Api\u003A\u003A\u0024api_version",
            "name": "api_version",
            "summary": "",
            "url": "classes/BizCuit-tBexioV2Api.html#property_api_version"
        },                {
            "fqsen": "\\BizCuit\\tBexioV3Api",
            "name": "tBexioV3Api",
            "summary": "",
            "url": "classes/BizCuit-tBexioV3Api.html"
        },                {
            "fqsen": "\\BizCuit\\tBexioV3Api\u003A\u003A\u0024api_version",
            "name": "api_version",
            "summary": "",
            "url": "classes/BizCuit-tBexioV3Api.html#property_api_version"
        },                {
            "fqsen": "\\BizCuit\\tBexioV4Api",
            "name": "tBexioV4Api",
            "summary": "",
            "url": "classes/BizCuit-tBexioV4Api.html"
        },                {
            "fqsen": "\\BizCuit\\tBexioV4Api\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Search\u0020request\u0020for\u0020version\u00204\u0020of\u0020the\u0020API.",
            "url": "classes/BizCuit-tBexioV4Api.html#method_search"
        },                {
            "fqsen": "\\BizCuit\\tBexioV4Api\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "List\u0020request\u0020for\u0020version\u00204\u0020of\u0020the\u0020API.",
            "url": "classes/BizCuit-tBexioV4Api.html#method_list"
        },                {
            "fqsen": "\\BizCuit\\tBexioV4Api\u003A\u003AgetIdName\u0028\u0029",
            "name": "getIdName",
            "summary": "Get\u0020ID\u0020name\u0020for\u0020version\u00204\u0020of\u0020the\u0020API.",
            "url": "classes/BizCuit-tBexioV4Api.html#method_getIdName"
        },                {
            "fqsen": "\\BizCuit\\tBexioV4Api\u003A\u003AnewQuery\u0028\u0029",
            "name": "newQuery",
            "summary": "Create\u0020new\u0020query\u0020for\u0020version\u00204\u0020of\u0020the\u0020API.",
            "url": "classes/BizCuit-tBexioV4Api.html#method_newQuery"
        },                {
            "fqsen": "\\BizCuit\\tBexioV4Api\u003A\u003A\u0024api_version",
            "name": "api_version",
            "summary": "",
            "url": "classes/BizCuit-tBexioV4Api.html#property_api_version"
        },                {
            "fqsen": "\\BizCuit\\tBexioCollection",
            "name": "tBexioCollection",
            "summary": "",
            "url": "classes/BizCuit-tBexioCollection.html"
        },                {
            "fqsen": "\\BizCuit\\tBexioCollection\u003A\u003AgetIdName\u0028\u0029",
            "name": "getIdName",
            "summary": "Return\u0020the\u0020property\u0020name\u0020used\u0020as\u0020unique\u0020id\u0020for\u0020this\u0020collection.",
            "url": "classes/BizCuit-tBexioCollection.html#method_getIdName"
        },                {
            "fqsen": "\\BizCuit\\tBexioCollection\u003A\u003AnewQuery\u0028\u0029",
            "name": "newQuery",
            "summary": "Create\u0020a\u0020new\u0020BXQuery\u0020object\u0020for\u0020this\u0020collection.",
            "url": "classes/BizCuit-tBexioCollection.html#method_newQuery"
        },                {
            "fqsen": "\\BizCuit\\tBexioCollection\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Search\u0020the\u0020collection.",
            "url": "classes/BizCuit-tBexioCollection.html#method_search"
        },                {
            "fqsen": "\\BizCuit\\tBexioCollection\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "List\u0020the\u0020collection.",
            "url": "classes/BizCuit-tBexioCollection.html#method_list"
        },                {
            "fqsen": "\\BizCuit\\tBexioObject",
            "name": "tBexioObject",
            "summary": "",
            "url": "classes/BizCuit-tBexioObject.html"
        },                {
            "fqsen": "\\BizCuit\\tBexioObject\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "Create\u0020a\u0020new\u0020BXObject.",
            "url": "classes/BizCuit-tBexioObject.html#method_new"
        },                {
            "fqsen": "\\BizCuit\\tBexioObject\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020an\u0020item\u0020in\u0020the\u0020collection.",
            "url": "classes/BizCuit-tBexioObject.html#method_delete"
        },                {
            "fqsen": "\\BizCuit\\tBexioObject\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020an\u0020item\u0020from\u0020the\u0020collection",
            "url": "classes/BizCuit-tBexioObject.html#method_get"
        },                {
            "fqsen": "\\BizCuit\\tBexioObject\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Set\u0020an\u0020item\u0020in\u0020the\u0020collection",
            "url": "classes/BizCuit-tBexioObject.html#method_set"
        },                {
            "fqsen": "\\BizCuit\\tBexioObject\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "\u005B\u0021\u0021\u0021\u005D\u0020Update\u0020an\u0020item\u0020in\u0020the\u0020collection",
            "url": "classes/BizCuit-tBexioObject.html#method_update"
        },                {
            "fqsen": "\\BizCuit\\tBexioArchiveable",
            "name": "tBexioArchiveable",
            "summary": "",
            "url": "classes/BizCuit-tBexioArchiveable.html"
        },                {
            "fqsen": "\\BizCuit\\tBexioArchiveable\u003A\u003Aarchive\u0028\u0029",
            "name": "archive",
            "summary": "",
            "url": "classes/BizCuit-tBexioArchiveable.html#method_archive"
        },                {
            "fqsen": "\\BizCuit\\tBexioArchiveable\u003A\u003Aunarchive\u0028\u0029",
            "name": "unarchive",
            "summary": "",
            "url": "classes/BizCuit-tBexioArchiveable.html#method_unarchive"
        },                {
            "fqsen": "\\BizCuit\\tBexioNumberObject",
            "name": "tBexioNumberObject",
            "summary": "",
            "url": "classes/BizCuit-tBexioNumberObject.html"
        },                {
            "fqsen": "\\BizCuit\\tBexioNumberObject\u003A\u003AgetByNumber\u0028\u0029",
            "name": "getByNumber",
            "summary": "",
            "url": "classes/BizCuit-tBexioNumberObject.html#method_getByNumber"
        },                {
            "fqsen": "\\BizCuit\\tBexioPDFObject",
            "name": "tBexioPDFObject",
            "summary": "",
            "url": "classes/BizCuit-tBexioPDFObject.html"
        },                {
            "fqsen": "\\BizCuit\\tBexioPDFObject\u003A\u003AgetPDF\u0028\u0029",
            "name": "getPDF",
            "summary": "",
            "url": "classes/BizCuit-tBexioPDFObject.html#method_getPDF"
        },                {
            "fqsen": "\\BizCuit\\tBexioProjectObject",
            "name": "tBexioProjectObject",
            "summary": "",
            "url": "classes/BizCuit-tBexioProjectObject.html"
        },                {
            "fqsen": "\\BizCuit\\tBexioProjectObject\u003A\u003AlistByProject\u0028\u0029",
            "name": "listByProject",
            "summary": "",
            "url": "classes/BizCuit-tBexioProjectObject.html#method_listByProject"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject",
            "name": "BXObject",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#method_getId"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#method_getType"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003AgetNumber\u0028\u0029",
            "name": "getNumber",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#method_getNumber"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003AtoJson\u0028\u0029",
            "name": "toJson",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#method_toJson"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003AchangesToJson\u0028\u0029",
            "name": "changesToJson",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#method_changesToJson"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#method___get"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#method___set"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003AID",
            "name": "ID",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#constant_ID"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003AnullableProperties",
            "name": "nullableProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#constant_nullableProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003AmapProperties",
            "name": "mapProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#constant_mapProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003Areadonly",
            "name": "readonly",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#constant_readonly"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003A\u0024changes",
            "name": "changes",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#property_changes"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\BXObject\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/BizCuit-BXObject-BXObject.html#property_content"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\ROObject",
            "name": "ROObject",
            "summary": "",
            "url": "classes/BizCuit-BXObject-ROObject.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\ROObject\u003A\u003AtoJson\u0028\u0029",
            "name": "toJson",
            "summary": "",
            "url": "classes/BizCuit-BXObject-ROObject.html#method_toJson"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\ROObject\u003A\u003AchangesToJson\u0028\u0029",
            "name": "changesToJson",
            "summary": "",
            "url": "classes/BizCuit-BXObject-ROObject.html#method_changesToJson"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\ROObject\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-ROObject.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\ROObject\u003A\u003Areadonly",
            "name": "readonly",
            "summary": "",
            "url": "classes/BizCuit-BXObject-ROObject.html#constant_readonly"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\File",
            "name": "File",
            "summary": "",
            "url": "classes/BizCuit-BXObject-File.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Bills",
            "name": "Bills",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Bills.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\ProjectType",
            "name": "ProjectType",
            "summary": "",
            "url": "classes/BizCuit-BXObject-ProjectType.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Title",
            "name": "Title",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Title.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Salutation",
            "name": "Salutation",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Salutation.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\ClientService",
            "name": "ClientService",
            "summary": "",
            "url": "classes/BizCuit-BXObject-ClientService.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Country",
            "name": "Country",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Country.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Country\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Country.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Country\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Country.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Country\u003A\u003AmapProperties",
            "name": "mapProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Country.html#constant_mapProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Contact",
            "name": "Contact",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Contact.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Contact\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Contact.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Contact\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Contact.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Contact\u003A\u003AnullableProperties",
            "name": "nullableProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Contact.html#constant_nullableProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\ContactRelation",
            "name": "ContactRelation",
            "summary": "",
            "url": "classes/BizCuit-BXObject-ContactRelation.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\ContactRelation\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-ContactRelation.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\ContactRelation\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-ContactRelation.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\AdditionalAddress",
            "name": "AdditionalAddress",
            "summary": "",
            "url": "classes/BizCuit-BXObject-AdditionalAddress.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\AdditionalAddress\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-AdditionalAddress.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\AdditionalAddress\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-AdditionalAddress.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Note",
            "name": "Note",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Note.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Note\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Note.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Note\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Note.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Project",
            "name": "Project",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Project.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Project\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Project.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Project\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Project.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Order",
            "name": "Order",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Order.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Order\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Order.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Order\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Order.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Invoice",
            "name": "Invoice",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Invoice.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Invoice\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Invoice.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Invoice\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Invoice.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Quote",
            "name": "Quote",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Quote.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Quote\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Quote.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\Quote\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-Quote.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\User",
            "name": "User",
            "summary": "",
            "url": "classes/BizCuit-BXObject-User.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\User\u003A\u003ANR",
            "name": "NR",
            "summary": "",
            "url": "classes/BizCuit-BXObject-User.html#constant_NR"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\User\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-User.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\PDF",
            "name": "PDF",
            "summary": "",
            "url": "classes/BizCuit-BXObject-PDF.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\PDF\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXObject-PDF.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\PDF\u003A\u003AtoJson\u0028\u0029",
            "name": "toJson",
            "summary": "",
            "url": "classes/BizCuit-BXObject-PDF.html#method_toJson"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\PDF\u003A\u003AchangesToJson\u0028\u0029",
            "name": "changesToJson",
            "summary": "",
            "url": "classes/BizCuit-BXObject-PDF.html#method_changesToJson"
        },                {
            "fqsen": "\\BizCuit\\BXObject\\PDF\u003A\u003AcreateProperties",
            "name": "createProperties",
            "summary": "",
            "url": "classes/BizCuit-BXObject-PDF.html#constant_createProperties"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\BXQuery",
            "name": "BXQuery",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-BXQuery.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\BXQuery\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-BXQuery.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\BXQuery\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-BXQuery.html#method_add"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\BXQuery\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-BXQuery.html#method_remove"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\BXQuery\u003A\u003Areplace\u0028\u0029",
            "name": "replace",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-BXQuery.html#method_replace"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\BXQuery\u003A\u003AtoJson\u0028\u0029",
            "name": "toJson",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-BXQuery.html#method_toJson"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\BXQuery\u003A\u003AgetRawQuery\u0028\u0029",
            "name": "getRawQuery",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-BXQuery.html#method_getRawQuery"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\BXQuery\u003A\u003AallowedCriteria",
            "name": "allowedCriteria",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-BXQuery.html#constant_allowedCriteria"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\BXQuery\u003A\u003A\u0024allowedField",
            "name": "allowedField",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-BXQuery.html#property_allowedField"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\BXQuery\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-BXQuery.html#property_query"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\ROObject",
            "name": "ROObject",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-ROObject.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\ROObject\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-ROObject.html#method_add"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\ContactGroup",
            "name": "ContactGroup",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-ContactGroup.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\ContactSector",
            "name": "ContactSector",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-ContactSector.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Salutation",
            "name": "Salutation",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Salutation.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Title",
            "name": "Title",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Title.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Payment",
            "name": "Payment",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Payment.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Unit",
            "name": "Unit",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Unit.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\StockLocation",
            "name": "StockLocation",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-StockLocation.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\BusinessActivity",
            "name": "BusinessActivity",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-BusinessActivity.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\CommunicationType",
            "name": "CommunicationType",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-CommunicationType.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Project",
            "name": "Project",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Project.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Project\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Project.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\File",
            "name": "File",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-File.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\File\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-File.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Contact",
            "name": "Contact",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Contact.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Contact\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Contact.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\ContactRelation",
            "name": "ContactRelation",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-ContactRelation.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\ContactRelation\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-ContactRelation.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\AdditionalAddress",
            "name": "AdditionalAddress",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-AdditionalAddress.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\AdditionalAddress\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-AdditionalAddress.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Quote",
            "name": "Quote",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Quote.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Quote\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Quote.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Order",
            "name": "Order",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Order.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Order\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Order.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Invoice",
            "name": "Invoice",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Invoice.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Invoice\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Invoice.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\InvoiceReminder",
            "name": "InvoiceReminder",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-InvoiceReminder.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\InvoiceReminder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-InvoiceReminder.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Account",
            "name": "Account",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Account.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Account\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Account.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Item",
            "name": "Item",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Item.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Item\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Item.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\StockArea",
            "name": "StockArea",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-StockArea.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\StockArea\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-StockArea.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Timesheet",
            "name": "Timesheet",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Timesheet.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Timesheet\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Timesheet.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Country",
            "name": "Country",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Country.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Country\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Country.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Language",
            "name": "Language",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Language.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Language\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Language.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Note",
            "name": "Note",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Note.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Note\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Note.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Task",
            "name": "Task",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Task.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Task\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Task.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\User",
            "name": "User",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-User.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-User.html#method___construct"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Bills",
            "name": "Bills",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Bills.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery\\Bills\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BizCuit-BXQuery-Bills.html#method___construct"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\BizCuit",
            "name": "BizCuit",
            "summary": "",
            "url": "namespaces/bizcuit.html"
        },                {
            "fqsen": "\\BizCuit\\BXObject",
            "name": "BXObject",
            "summary": "",
            "url": "namespaces/bizcuit-bxobject.html"
        },                {
            "fqsen": "\\BizCuit\\BXQuery",
            "name": "BXQuery",
            "summary": "",
            "url": "namespaces/bizcuit-bxquery.html"
        }            ]
);
